#pragma once

#include "CoreMinimal.h"
#include "ChunkTypes.generated.h"

/**
 * 区块类别。
 * Gameplay  : 玩法块，参与连接图、玩家进入判定与敌人状态持久化。
 * Background: 背景装饰块，不参与玩家判定，由玩法块的 VisibleFromChunks 引用（OR 加载）。
 * Persistent: 常驻块，永远加载（HUD、全局系统），不进连接图。
 */
UENUM(BlueprintType)
enum class EChunkCategory : uint8
{
	Gameplay	UMETA(DisplayName = "Gameplay"),
	Background	UMETA(DisplayName = "Background"),
	Persistent	UMETA(DisplayName = "Persistent")
};

/** 单个区块的描述信息（编辑器工具自动计算包围盒，运行时常量数据）。 */
USTRUCT(BlueprintType)
struct FChunkInfo
{
	GENERATED_BODY()

	/** 子关卡包名（例如 /Game/Maps/Chunk_001），全局唯一标识。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FName LevelName;

	/** 显示名（仅编辑用途）。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FString DisplayName;

	/** 世界包围盒（编辑器工具自动计算）。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FBox WorldBounds = FBox(ForceInit);

	/** 沿移动轴的区间 [Min, Max)，半开区间约定，边界点只属于右侧区块。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FVector2D XRange = FVector2D::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	EChunkCategory Category = EChunkCategory::Gameplay;

	/** 背景块专用：哪些玩法块"看得到"它（任一加载则本块加载，OR 语义）。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	TArray<FName> VisibleFromChunks;

	/** 背景块专用：全局背景（如天空、最远山），永远可见。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	bool bVisibleFromAll = false;

	/** 出生块：PIE/运行开始时玩家所在的区块。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	bool bStartChunk = false;

	/** 编辑器工具是否自动刷新该块的包围盒（手动摆放的块可关闭）。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	bool bAutoBounds = true;

	bool IsValidChunk() const { return !LevelName.IsNone() && WorldBounds.IsValid; }
};

/** 区块连接（图的一条无向边）：只表示两个区块"相连"，不区分方向/进/出。
 *  相邻的区块互相加载；互不相连的区块组永远不会同时加载（传送除外）。
 *  bAutoGenerated 的边由工具自动生成，重跑自动建图时会被刷新。 */
USTRUCT(BlueprintType)
struct FChunkConnection
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FName FromLevel;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FName ToLevel;

	/** 自动生成的边，重跑 Auto-Graph 时会被刷新；手动边永远保留。 */
	UPROPERTY(VisibleAnywhere, Category = "Chunk")
	bool bAutoGenerated = false;
};

/** 敌人/可保存 Actor 的最小状态单元（由 UChunkStateStore 按区块存储）。 */
USTRUCT(BlueprintType)
struct FChunkEnemySaveData
{
	GENERATED_BODY()

	/** 唯一 ID：区块名 + Actor 在子关卡内的名字（编辑保存后稳定）。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FString EnemyId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	float Health = 100.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	bool bDead = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	FTransform SavedTransform = FTransform::Identity;

	/** 扩展字节（蓝图/子类可写入自定义数据）。 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	TArray<uint8> CustomData;
};

/** 状态列表包装（UHT 不支持 TMap 直接以 TArray 为值，用结构体包装）。 */
USTRUCT(BlueprintType)
struct FChunkEnemySaveDataList
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chunk")
	TArray<FChunkEnemySaveData> Items;
};
