#include "ChunkGraphEdGraph.h"

#include "EdGraph/EdGraphNode.h"

#include "ChunkGraphAsset.h"
#include "ChunkGraphNode.h"

namespace ChunkGraphConverterPrivate
{
	UChunkGraphNode* FindNode(UChunkGraphEdGraph* Graph, FName ChunkName)
	{
		if (!Graph)
		{
			return nullptr;
		}
		for (UEdGraphNode* BaseNode : Graph->Nodes)
		{
			UChunkGraphNode* Node = Cast<UChunkGraphNode>(BaseNode);
			if (Node && Node->ChunkName == ChunkName)
			{
				return Node;
			}
		}
		return nullptr;
	}
}

void FChunkGraphConverter::BuildNodesFromAsset(UChunkGraphAsset* Asset, UChunkGraphEdGraph* Graph)
{
	using namespace ChunkGraphConverterPrivate;

	if (!Asset || !Graph)
	{
		return;
	}
	Graph->Modify();

	// 删除资产中已不存在的节点
	for (UEdGraphNode* BaseNode : Graph->Nodes)
	{
		UChunkGraphNode* Node = Cast<UChunkGraphNode>(BaseNode);
		if (!Node)
		{
			Graph->RemoveNode(BaseNode);
			continue;
		}
		if (!Asset->FindChunkInfoPtr(Node->ChunkName))
		{
			Graph->RemoveNode(Node);
		}
	}

	// 创建/更新节点（已有节点保留位置）
	int32 GameplayIndex = 0;
	int32 BackgroundIndex = 0;
	int32 PersistentIndex = 0;
	for (const FChunkInfo& Info : Asset->Chunks)
	{
		UChunkGraphNode* Node = FindNode(Graph, Info.LevelName);
		if (!Node)
		{
			Node = NewObject<UChunkGraphNode>(Graph, UChunkGraphNode::StaticClass(), NAME_None, RF_Transactional);
			Node->CreateNewGuid();
			Node->ChunkName = Info.LevelName;
			Graph->AddNode(Node, /*bUserAction*/ false, /*bSelectNewNode*/ false);
			Node->PostPlacedNewNode();
			Node->AllocateDefaultPins();

			// 默认布局：玩法块一排、背景块上一排、常驻块右侧
			switch (Info.Category)
			{
			case EChunkCategory::Gameplay:
				Node->NodePosX = 160 + GameplayIndex * 300;
				Node->NodePosY = 420;
				++GameplayIndex;
				break;
			case EChunkCategory::Background:
				Node->NodePosX = 160 + BackgroundIndex * 300;
				Node->NodePosY = 80;
				++BackgroundIndex;
				break;
			default:
				Node->NodePosX = 160 + PersistentIndex * 300;
				Node->NodePosY = 80;
				++PersistentIndex;
				break;
			}
		}
		Node->SyncFromChunkInfo(Info);
	}

	// 重建连接数据（无向；背景引用独立存放）
	Graph->GraphConnections = Asset->Connections;
	Graph->GraphBackgroundRefs.Reset();
	for (const FChunkInfo& BG : Asset->Chunks)
	{
		if (BG.Category != EChunkCategory::Background)
		{
			continue;
		}
		for (const FName& Owner : BG.VisibleFromChunks)
		{
			FChunkConnection Ref;
			Ref.FromLevel = BG.LevelName;
			Ref.ToLevel = Owner;
			Graph->GraphBackgroundRefs.Add(Ref);
		}
	}

	Graph->NotifyGraphChanged();
}

void FChunkGraphConverter::SyncAssetFromGraph(UChunkGraphAsset* Asset, UChunkGraphEdGraph* Graph)
{
	if (!Asset || !Graph)
	{
		return;
	}

	// 1) 玩法连接：无向去重（同一条边不管方向只保留一条）
	TArray<FChunkConnection> NewConnections;
	for (const FChunkConnection& Conn : Graph->GraphConnections)
	{
		const bool bExists = NewConnections.ContainsByPredicate([&](const FChunkConnection& C)
		{
			return (C.FromLevel == Conn.FromLevel && C.ToLevel == Conn.ToLevel) ||
				(C.FromLevel == Conn.ToLevel && C.ToLevel == Conn.FromLevel);
		});
		if (bExists)
		{
			continue;
		}
		FChunkConnection Out = Conn;
		// 保留旧的自动/手动标记（按无序配对匹配）
		for (const FChunkConnection& Old : Asset->Connections)
		{
			if ((Old.FromLevel == Conn.FromLevel && Old.ToLevel == Conn.ToLevel) ||
				(Old.FromLevel == Conn.ToLevel && Old.ToLevel == Conn.FromLevel))
			{
				Out.bAutoGenerated = Old.bAutoGenerated;
				break;
			}
		}
		NewConnections.Add(Out);
	}
	Asset->Connections = NewConnections;

	// 2) 背景引用
	for (FChunkInfo& BG : Asset->Chunks)
	{
		if (BG.Category == EChunkCategory::Background)
		{
			BG.VisibleFromChunks.Reset();
		}
	}
	for (const FChunkConnection& Ref : Graph->GraphBackgroundRefs)
	{
		FChunkInfo* BG = nullptr;
		for (FChunkInfo& I : Asset->Chunks)
		{
			if (I.LevelName == Ref.FromLevel && I.Category == EChunkCategory::Background)
			{
				BG = &I;
				break;
			}
		}
		if (BG)
		{
			BG->VisibleFromChunks.AddUnique(Ref.ToLevel);
		}
	}

	// 3) 节点属性同步回资产
	for (UEdGraphNode* BaseNode : Graph->Nodes)
	{
		UChunkGraphNode* Node = Cast<UChunkGraphNode>(BaseNode);
		if (!Node || Node->ChunkName.IsNone())
		{
			continue;
		}
		FChunkInfo* Info = nullptr;
		for (FChunkInfo& I : Asset->Chunks)
		{
			if (I.LevelName == Node->ChunkName)
			{
				Info = &I;
				break;
			}
		}
		if (Info)
		{
			Node->SyncToChunkInfo(*Info);
		}
	}

	Asset->MarkPackageDirty();
}

void FChunkGraphConverter::AutoLayout(UChunkGraphEdGraph* Graph)
{
	if (!Graph)
	{
		return;
	}
	// 按类型分列
	TArray<UChunkGraphNode*> Gameplay, Background, Persistent;
	for (UEdGraphNode* BaseNode : Graph->Nodes)
	{
		if (UChunkGraphNode* Node = Cast<UChunkGraphNode>(BaseNode))
		{
			switch (Node->Category)
			{
			case EChunkCategory::Gameplay: Gameplay.Add(Node); break;
			case EChunkCategory::Background: Background.Add(Node); break;
			default: Persistent.Add(Node); break;
			}
		}
	}
	Gameplay.Sort([](const UChunkGraphNode& A, const UChunkGraphNode& B) { return A.XRange.X < B.XRange.X; });
	Background.Sort([](const UChunkGraphNode& A, const UChunkGraphNode& B) { return A.XRange.X < B.XRange.X; });

	int32 X = 160;
	for (UChunkGraphNode* Node : Gameplay)
	{
		Node->NodePosX = X;
		Node->NodePosY = 420;
		X += 300;
	}
	X = 160;
	for (UChunkGraphNode* Node : Background)
	{
		Node->NodePosX = X;
		Node->NodePosY = 80;
		X += 300;
	}
	X = 160;
	for (UChunkGraphNode* Node : Persistent)
	{
		Node->NodePosX = X;
		Node->NodePosY = 700;
		X += 300;
	}
	Graph->NotifyGraphChanged();
}
