#pragma once

#include "CoreMinimal.h"
#include "EdGraph/EdGraph.h"
#include "ChunkTypes.h"
#include "ChunkGraphEdGraph.generated.h"

class UChunkGraphAsset;

/**
 * 区块连接图（编辑器用）：节点 + 连接数据的容器，随图资产保存。
 * 连接不存引脚（无方向概念），直接存无向连接对，由画线策略按"节点边缘最近点"绘制。
 */
UCLASS()
class UChunkGraphEdGraph : public UEdGraph
{
	GENERATED_BODY()

public:
	/** 玩法块之间的无向连接（图编辑器数据）。 */
	UPROPERTY()
	TArray<FChunkConnection> GraphConnections;

	/** 背景引用（背景块 -> 玩法块），写回 FChunkInfo::VisibleFromChunks。 */
	UPROPERTY()
	TArray<FChunkConnection> GraphBackgroundRefs;
};

/**
 * 图 <-> 资产 转换工具（编辑器用）。
 */
class FChunkGraphConverter
{
public:
	/** 按资产生成/补齐节点与连接数据（保留已有节点位置）。 */
	static void BuildNodesFromAsset(UChunkGraphAsset* Asset, UChunkGraphEdGraph* Graph);

	/** 把图的连接数据与节点属性写回资产（无向去重；保留 bAutoGenerated）。 */
	static void SyncAssetFromGraph(UChunkGraphAsset* Asset, UChunkGraphEdGraph* Graph);

	/** 按 X 区间自动布局所有节点。 */
	static void AutoLayout(UChunkGraphEdGraph* Graph);
};
