#pragma once

#include "CoreMinimal.h"
#include "ChunkTypes.h"

class UChunkGraphAsset;
class UWorld;
struct FChunkInfo;

/**
 * 编辑器侧的图构建/校验工具（纯静态函数）。
 */
class FChunkGraphBuilder
{
public:
	/** 扫描当前编辑器世界的流送子关卡，返回 LevelName(包名) -> 包围盒。 */
	static void CollectStreamingLevelBounds(UWorld* World, TMap<FName, FBox>& OutBounds, TArray<FName>& OutMissingLevels);

	/** 用关卡列表刷新资产中的 ChunkInfo（保留已有分类/引用/标记；新块按命名约定自动分类）。 */
	static void RefreshChunkInfos(UChunkGraphAsset* Asset, UWorld* World);

	/** 自动连边：只刷新 bAutoGenerated 的边，手动边保留。 */
	static void AutoConnect(UChunkGraphAsset* Asset);

	/** 背景块自动分配 VisibleFromChunks（与背景区间相交的所有玩法块）。 */
	static void AutoAssignBackgrounds(UChunkGraphAsset* Asset);

	/** 校验并返回错误/警告消息列表。 */
	static TArray<FText> Validate(UChunkGraphAsset* Asset, UWorld* World);

	/** 按命名约定建议分类（BG_/BKG_ 前缀 -> Background）。 */
	static EChunkCategory SuggestCategory(FName LevelName);

private:
	static bool IsAdjacent(const UChunkGraphAsset* Asset, const FChunkInfo& A, const FChunkInfo& B);
	static FVector2D ProjectRange(const FBox& Bounds, EAxis::Type Axis);
};
